# Generated by Django 4.0.1 on 2023-03-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
