# Generated by Django 4.0.1 on 2023-03-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='portal_id',
            field=models.IntegerField(default=1, max_length=254, unique=True, verbose_name='portal_id'),
            preserve_default=False,
        ),
    ]
