# Generated by Django 4.0.1 on 2023-03-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_customuser_portal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='portal_id',
            field=models.IntegerField(unique=True, verbose_name='portal_id'),
        ),
    ]
