# Generated by Django 4.0.1 on 2023-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenrollment',
            name='enrolled',
            field=models.BooleanField(default=True),
        ),
    ]
