# Generated by Django 4.0.1 on 2022-02-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
