# Generated by Django 4.0.1 on 2022-01-23 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_classenrollment_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 9, 11, 13, 104824)),
        ),
    ]
