# Generated by Django 4.0.1 on 2022-01-23 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 28, 8, 379712)),
        ),
    ]
