# Generated by Django 4.0.1 on 2022-01-29 08:24

import classmenu.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=classmenu.models.get_file_upload_location)),
                ('location_hint', models.CharField(choices=[('public', 'Public')], default='public', max_length=10)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.class')),
            ],
        ),
        migrations.CreateModel(
            name='MessagePublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.class')),
                ('files', models.ManyToManyField(to='classmenu.File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
