# Generated by Django 4.0.1 on 2022-02-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmenu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagepublic',
            old_name='url',
            new_name='urls',
        ),
    ]
