# Generated by Django 4.0.1 on 2022-01-29 08:28

import classmenu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=500, upload_to=classmenu.models.get_file_upload_location),
        ),
    ]
