# Generated by Django 4.0.1 on 2022-01-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmenu', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='location_hint',
            field=models.CharField(choices=[('public', 'Public'), ('assignment', 'Assignment'), ('response', 'Response')], max_length=10),
        ),
    ]
