# Generated by Django 4.0.1 on 2022-02-01 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classmenu', '0002_rename_url_messagepublic_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepublic',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
