# Generated by Django 4.0.1 on 2022-02-01 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmenu', '0003_messagepublic_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagepublic',
            old_name='time',
            new_name='date',
        ),
    ]
