# Generated by Django 4.0.1 on 2022-02-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmenu', '0004_rename_time_messagepublic_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagepublic',
            name='files',
            field=models.ManyToManyField(blank=True, to='classmenu.File'),
        ),
        migrations.AlterField(
            model_name='messagepublic',
            name='urls',
            field=models.ManyToManyField(blank=True, to='classmenu.Url'),
        ),
    ]
