# Generated by Django 4.0.1 on 2022-02-05 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_class_date_started'),
        ('classmenu', '0005_alter_messagepublic_files_alter_messagepublic_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_due', models.DateTimeField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.class')),
                ('files', models.ManyToManyField(blank=True, to='classmenu.File')),
                ('urls', models.ManyToManyField(blank=True, to='classmenu.Url')),
            ],
        ),
    ]
