# Generated by Django 4.0.1 on 2022-02-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmenu', '0011_alter_assignment_date_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='total_marks',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
