# Generated by Django 4.0.1 on 2022-02-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmenu', '0012_alter_assignment_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
