# Generated by Django 4.0.1 on 2022-02-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmenu', '0016_poll_date_added_polleddetail_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagepublic',
            old_name='date',
            new_name='date_added',
        ),
    ]
