# Generated by Django 4.0.1 on 2022-02-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmenu', '0017_rename_date_messagepublic_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
